
spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/postgres
    username: user
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: pasieka2.0banulskicieplinski@gmail.com
    password: jnpaxvxfjbhrhjqp
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

#logging:
#  level:
#    root: trace